#1. How many accidents were there inMadrid in 2013?

PREFIX property: <http://example.org/myVocabulary#> 
PREFIX qb: <http://purl.org/linked-data/cube#>  
SELECT (SUM(?x) AS ?total) WHERE { 
   ?obs a qb:Observation ; 
   property:numberOfAccidents ?x . 
} 

#2. Give me the number of accidents in Usera for each type of accident 

PREFIX property: <http://example.org/myVocabulary#> 
PREFIX qb: <http://purl.org/linked-data/cube#>  
SELECT (SUM(xsd:int(?x)) AS ?totalAccidentesUsera) ?tipoAccidente WHERE {  
  ?obs a qb:Observation ; 
  property:hasAccidentType ?tipoAccidente;
  property:relatedDistrict "USERA";
  property:numberOfAccidents ?x.
} GROUP BY (?tipoAccidente)

#3. Give me the number of multiple collisions for each district 

PREFIX property: <http://example.org/myVocabulary#> 
PREFIX qb: <http://purl.org/linked-data/cube#>  
SELECT (SUM(xsd:int(?x)) AS ?totalAccidentesMulCol) ?tipoDistrito WHERE {  
  ?obs a qb:Observation ; 
  property:relatedDistrict ?tipoDistrito;
  property:hasAccidentType property:MultipleCollision;
  property:numberOfAccidents ?x.
} GROUP BY (?tipoDistrito)

#4. Which is the district were the number of bicycle falls was higher in 2013? 

PREFIX property: <http://example.org/myVocabulary#> 
PREFIX qb: <http://purl.org/linked-data/cube#> 
SELECT (SUM(xsd:int(?x)) AS ?totalAccidentesBici) ?distrito WHERE { 
  ?obs a qb:Observation ; 
  property:relatedDistrict ?distrito; 
  property:hasAccidentType property:BicycleFall ;
  property:numberOfAccidents ?x . 
} GROUP BY (?distrito)

#5. Give me the districts with more than 500 accidents in 2013 


